export const dataalat = [
  {
    name: 'Oli',
    jumlah: 20,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-22',
  },
  {
    name: 'Tang Criping',
    jumlah: 202,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-02-22',
  },
  {
    name: 'Monitor',
    jumlah: 220,
    kondisi: 'Rusak',
    status: 'Tidak',
    tanggal: '2020-07-29',
  },
  {
    name: 'Komputer',
    jumlah: 220,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-12',
  },
  {
    name: 'Keyboard',
    jumlah: 210,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-21',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Rusak',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Rusak',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Rusak',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Rusak',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    name: 'Komputer',
    jumlah: 220,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-12',
  },
];

export const dataSiswa = [
  {
    name: 'Anhar Fadilah',
    angkatan: 2020,
    class: 'Tataboga A',
  },
  {
    name: 'Anhar Fadilah',
    angkatan: 2020,
    class: 'Tataboga A',
  },
  {
    name: 'Arif Cepmek',
    angkatan: 2020,
    class: 'Tataboga A',
  },
  {
    name: 'Anhar Fadilah',
    angkatan: 2020,
    class: 'Tataboga A',
  },
  {
    name: 'Firmansyah',
    angkatan: 2021,
    class: 'TKJ B',
  },
  {
    name: 'Firmansyah',
    angkatan: 2021,
    class: 'TKJ B',
  },
  {
    name: 'Firmansyah',
    angkatan: 2021,
    class: 'TKJ B',
  },
  {
    name: 'Raihan Balfas',
    angkatan: 2018,
    class: 'TKJ A',
  },
  {
    name: 'M. Rifki Tang Kriping',
    angkatan: 2020,
    class: 'TKJ C',
  },
  {
    name: 'Annas Ter Panas Panas',
    angkatan: 2020,
    class: 'TKJ C',
  },
];

export const dataGuru = [
  {
    name: 'Anhar Fadilah',
    nik: '8126398162',
    genre: 'Laki-laki',
    mapel: 'Metodologi Penelitian',
  },
  {
    name: 'Anhar Fadilah',
    nik: '8126398162',
    genre: 'Laki-laki',
    mapel: 'Pemrograman Web',
  },
  {
    name: 'Pevita Pearce',
    nik: '127312382',
    genre: 'Perempuan',
    mapel: 'Pemrograman Mobile',
  },
  {
    name: 'Jagoan Neon',
    nik: '4234312382',
    genre: 'Perempuan',
    mapel: 'Imlementasi Nextjs',
  },
  {
    name: 'Firmansyah',
    nik: '4234312382',
    genre: 'Laki-laki',
    mapel: 'Menjadi suami baik',
  },
  {
    name: 'Superman',
    nik: '4234312382',
    genre: 'Laki-laki',
    mapel: 'Praktek Penerbangan',
  },
  {
    name: 'Firmansyah',
    nik: '4234312382',
    genre: 'Laki-laki',
    mapel: 'Perternakan Kalilawar',
  },
  {
    name: 'Thor',
    nik: '4234312382',
    genre: 'Laki-laki',
    mapel: 'Arus Bolak-Balik',
  },
  {
    name: 'M. Rifki Tang Kriping',
    nik: '4234312382',
    genre: 'Laki-laki',
    mapel: 'Perternakan Kalilawar',
  },
  {
    name: 'Black Adam',
    nik: '4234312382',
    genre: 'Laki-laki',
    mapel: 'How to be stronger',
  },
];
export const dataPengajuan = [
  {
    name: 'Oli',
    jumlah: 20,
    pengaju: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    status: 'Diproses',
  },
  {
    name: 'Tang Criping',
    jumlah: 202,
    keterangan: 'Untuk praktek anak-anak',
    pengaju: 'Anhar Fadilah',
    kondisi: 'Baik',
    status: 'Ditolak',
    tanggal: '2020-02-22',
  },
  {
    name: 'Monitor',
    jumlah: 220,
    pengaju: 'Firmansyah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    status: 'Diterima',
  },
  {
    name: 'Komputer',
    jumlah: 220,
    pengaju: 'Rifki Riskun',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    status: 'Diterima',
  },
  {
    name: 'Keyboard',
    jumlah: 210,
    pengaju: 'Rifki Riskun',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-21',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Anas panas',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Fikri aulia',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Putra bukan putri',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Putra bukan putri',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Ditolak',
  },
  {
    name: 'Komputer',
    jumlah: 220,
    pengaju: 'Putra bukan putri',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diterima',
  },
];
export const dataPengembalian = [
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Selesai',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Selesai',
    tanggal: '2020-07-22',
  },
  {
    peminjam: 'Anhar Fadilah',
    barang: 'Oli',
    kembali: 20,
    rusak: 2,
    hilang: 1,
    status: 'Proses',
    tanggal: '2020-07-22',
  },
];
export const dataPraktek = [
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Ir. Soekarno Hatta',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
  {
    mapel: 'Olahraga',
    kelas: 'TKJ A',
    angkatan: 2020,
    tanggal: 'Senin, 02 Desember 2019',
    waktu: '07:30 - 09:45 WIB',
    pengajar: 'Mustamin S.pd S. ST',
    tempat: 'Di bulan',
  },
];

export const dataSupplier = [
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
  {
    name: 'Aris Toteles',
    asal: 'Jakarta Selatan',
    alamat: 'Depok, jln. Kemerdekaan, Jakarta Selatan',
    noHp: '082359029829',
  },
];
export const dataBarangSupplier = [
  {
    alat: 'Oli',
    penerima: 'Megawati',
    jumlah: 20,
    tanggal: '10-11-2011',
    name: 'Aris Toteles',
  },
  {
    alat: 'Leptop',
    penerima: 'Megawati',
    jumlah: 20,
    tanggal: '10-11-2011',
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    tanggal: '10-11-2011',
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    tanggal: '10-11-2011',
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    name: 'Aris Toteles',
  },
  {
    alat: 'Komputer',
    penerima: 'Megawati',
    jumlah: 20,
    name: 'Aris Toteles',
  },
];

export const dataPengadaan = [
  {
    name: 'Oli',
    jumlah: 20,
    pengaju: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    status: 'Diproses',
  },
  {
    name: 'Tang Criping',
    jumlah: 202,
    keterangan: 'Untuk praktek anak-anak',
    pengaju: 'Anhar Fadilah',
    kondisi: 'Baik',
    status: 'Ditolak',
    tanggal: '2020-02-22',
  },
  {
    name: 'Monitor',
    jumlah: 220,
    pengaju: 'Firmansyah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    status: 'Diterima',
  },
  {
    name: 'Komputer',
    jumlah: 220,
    pengaju: 'Rifki Riskun',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    status: 'Diterima',
  },
  {
    name: 'Keyboard',
    jumlah: 210,
    pengaju: 'Rifki Riskun',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-21',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Anas panas',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Fikri aulia',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Putra bukan putri',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diproses',
  },
  {
    name: 'Tank Baja',
    jumlah: 201,
    pengaju: 'Putra bukan putri',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Ditolak',
  },
  {
    name: 'Komputer',
    jumlah: 220,
    pengaju: 'Putra bukan putri',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2021-03-24',
    status: 'Diterima',
  },
];
export const dataBarangRusak = [
  {
    barang: 'Oli',
    jumlah: 20,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Tang Criping',
    jumlah: 20,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Monitor',
    jumlah: 20,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Komputer',
    jumlah: 20,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Keyboard',
    jumlah: 20,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Tank Baja',
    jumlah: 220,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Tank Baja',
    jumlah: 50,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Tank Baja',
    jumlah: 20,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Tank Baja',
    jumlah: 201,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
  {
    barang: 'Tank Baja',
    jumlah: 22,
    name: 'Anhar Fadilah',
    keterangan: 'Untuk praktek anak-anak',
    tanggal: '2020-07-22',
    harga: 23000,
  },
];

export const dataBarangMasuk = [
  {
    barang: 'Oli',
    jumlah: 20,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-22',
  },
  {
    barang: 'Tang Criping',
    jumlah: 202,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-02-22',
  },
  {
    barang: 'Monitor',
    jumlah: 220,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-22',
  },
  {
    barang: 'Komputer',
    jumlah: 220,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-22',
  },
  {
    barang: 'Keyboard',
    jumlah: 210,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2020-07-21',
  },
  {
    barang: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    barang: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    barang: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    barang: 'Tank Baja',
    jumlah: 201,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
  {
    barang: 'Komputer',
    jumlah: 220,
    kondisi: 'Baik',
    status: 'Ada',
    tanggal: '2021-03-24',
  },
];
